version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: matcha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app  # Mount backend source code for HMR
      - /usr/src/app/node_modules  # Exclude node_modules to avoid issues with host dependencies
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app  # Mount frontend source code for HMR
      - /usr/src/app/node_modules  # Exclude node_modules for the same reason as above
    networks:
      - app-network
  

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
